name: 'Test Core Screenshot'
description: 'Test Core Screenshot'
inputs:
  shard:
    description: 'Playwright Test Shard (ex: 2)'
  totalShards:
    description: 'Playwright total number of test shards (ex: 4)'
  update:
    description: 'Whether or not to update the update the reference snapshots'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Cache Core Node Modules
      uses: actions/cache@v2
      env:
        cache-name: core-node-modules
      with:
        path: ./core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./core/package-lock.json') }}-v2
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core-src
        path: ./core
        filename: CoreSrc.zip
    - name: Install Playwright Dependencies
      run: npx playwright install
      shell: bash
      working-directory: ./core
    - name: Test
      run: |
        args=(
          --shard=${{ inputs.shard }}/${{ inputs.totalShards }}
        )

        if [ "${{ inputs.update }}" = "true" ]; then
          args+=(--update-snapshots)
        fi

        npx playwright test ${args}
      shell: bash
      working-directory: ./core
    - name: Push Snapshot Updates
      if: inputs.update == "true"
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "test(): updated snapshots from shard ${{ inputs.shard }} of ${{ inputs.totalShards }}"
        git push
      shell: bash
      working-directory: ./core
    - name: Archive Test Results
      # The always() ensures that this step
      # runs even if the previous step fails.
      # We want the test results to be archived
      # even if the test fails in the previous
      # step, otherwise there would be no way
      # to debug these tests.
      if: inputs.update != "true"
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: test-core-screenshot (${{ inputs.shard }}, ${{ inputs.totalShards }})
        output: core/TestResults-${{ inputs.shard }}-${{ inputs.totalShards }}.zip
        paths: core/playwright-report
